services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      - db_network
    depends_on:
      - postgres

      
  postgres:
    image: postgres:latest
    hostname: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: multi-tenant
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: unless-stopped
    networks:
      - db_network
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped
    networks:
      - db_network
      
networks:
  db_network:
